apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: naksito03/auth:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          env:
            # gRPC server port
            - name: AUTH_PORT
              value: "8080"

            # 🔥 REQUIRED — fixes CrashLoopBackOff
            - name: JWT_SECRET
              value: "dev-super-secret-jwt-key-64-charactes-long-change-me-now"

            # Users service (gRPC)
            - name: USERS_HOST
              value: "users"
            - name: USERS_PORT
              value: "8081"

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: auth
  labels:
    app: auth
spec:
  selector:
    app: auth
  ports:
    - name: grpc
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodeport: 30080
