services:
  auth:
    image: naksito03/auth-service
    tag: 2.0.0
  users:
    image: naksito03/users-service
    tag: 2.0.0
  appointments:
    image: naksito03/appointments-service
    tag: 2.0.0
  api:
    image: naksito03/api-service
    tag: 2.0.0
  frontend:
    image: naksito03/frontend-service
    tag: 2.0.1
